"use client";

/**
 * An interactive .stl model viewer — orbit, zoom, axis gizmo, and optionally a
 * file picker so a visitor can drop in their own model.
 *
 * Proven as a spike in the old `/stl-lab` sandbox and kept when the labs were
 * removed, because a real 3D viewer is wanted on a project page later (see the
 * note in `app/projects/loco/sections/Fix.tsx`, which currently shows stills
 * where this would go). Nothing renders it yet — this is a component waiting
 * for a home, not dead code.
 *
 * The three.js scene lives in `./Scene.tsx` and is loaded with
 * `next/dynamic({ ssr: false })` rather than imported directly: three.js needs
 * a real DOM/WebGL context, which doesn't exist during Next's server render, so
 * importing it eagerly would throw or hydrate-mismatch. Per the Next.js docs
 * (`node_modules/next/dist/docs/01-app/02-guides/lazy-loading.md`), `ssr: false`
 * on `next/dynamic` must be called from a Client Component — hence the
 * `"use client"` here rather than on a Server Component wrapper.
 *
 * Costs nothing until it is used: the dynamic import means three,
 * `@react-three/fiber` and `@react-three/drei` are only fetched by a page that
 * actually mounts this.
 */

import { useCallback, useEffect, useRef, useState, type ChangeEvent } from "react";
import dynamic from "next/dynamic";
import styles from "./stl.module.css";

const Scene = dynamic(() => import("./Scene"), {
  ssr: false,
  loading: () => <div className={styles.loading}>Loading scene…</div>,
});

/** Procedurally generated by `scripts/generate-test-stl.mjs`. */
export const TEST_MODEL_URL = "/stl/icosahedron.stl";

export default function StlViewer({
  modelUrl = TEST_MODEL_URL,
  allowUpload = false,
  height,
  label,
}: {
  /** Path to the .stl to show. Defaults to the generated test icosahedron. */
  modelUrl?: string;
  /** Adds a file picker so a visitor can load their own model. */
  allowUpload?: boolean;
  /** Stage height, any CSS length. Defaults to `32rem`. */
  height?: string;
  /** Caption beside the upload control. Ignored when `allowUpload` is false. */
  label?: string;
}) {
  /*
   * The uploaded file, if there is one — held separately from `modelUrl`
   * rather than copied into a single `url` state that an effect keeps in sync.
   * Syncing a prop into state is what `react-hooks/set-state-in-effect`
   * (correctly) rejects, and it also loses: a parent swapping `modelUrl` after
   * mount would be silently ignored. Deriving instead means the prop is always
   * live, and an upload simply takes precedence until it is cleared.
   */
  const [upload, setUpload] = useState<{ url: string; name: string } | null>(null);

  const url = upload?.url ?? modelUrl;
  const name = upload?.name ?? label ?? "";

  // Tracks the blob URL from the last uploaded file so it can be revoked —
  // either when a new file replaces it or the component unmounts — instead of
  // leaking it for the life of the tab.
  const objectUrlRef = useRef<string | null>(null);

  useEffect(() => {
    return () => {
      if (objectUrlRef.current) URL.revokeObjectURL(objectUrlRef.current);
    };
  }, []);

  const handleFileChange = useCallback((event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    event.target.value = ""; // allow re-selecting the same file twice in a row
    if (!file) return;

    if (objectUrlRef.current) URL.revokeObjectURL(objectUrlRef.current);

    const next = URL.createObjectURL(file);
    objectUrlRef.current = next;
    setUpload({ url: next, name: file.name });
  }, []);

  return (
    <div
      className={styles.viewer}
      style={height ? ({ "--stl-height": height } as React.CSSProperties) : undefined}
    >
      {allowUpload && (
        <div className={styles.bar}>
          <label className={styles.upload}>
            Load .stl
            <input
              type="file"
              accept=".stl"
              className={styles.uploadInput}
              onChange={handleFileChange}
            />
          </label>
          {name && <span className={styles.label}>{name}</span>}
        </div>
      )}

      <div className={styles.stage}>
        <Scene modelUrl={url} />
      </div>
    </div>
  );
}
